version: "3"

services:
  cups:
    container_name: ${DOCKER_NAME_PREFIX}_${DOCKER_CUPS_SERVICE_NAME}
    build:
      context: .
      dockerfile: Cups.Dockerfile
      args:
        CUPS_ADMIN_USER: ${CUPS_ADMIN_USER}
        CUPS_ADMIN_PASSWORD: ${CUPS_ADMIN_PASSWORD}
    ports:
      - "${DOCKER_CUPS_SERVICE_PORT}:631"
    volumes:
      - ./cupsd.conf:/etc/cups/cupsd.conf
    environment:
      CUPS_ADMIN: ${CUPS_ADMIN_USER}
      CUPS_ADMIN_PASS: ${CUPS_ADMIN_PASSWORD}
    networks:
      - network

  caddy:
    container_name: ${DOCKER_NAME_PREFIX}_${DOCKER_CADDY_SERVICE_NAME}
    build:
      context: .
      dockerfile: Caddy.Dockerfile
    ports:
      - "${DOCKER_CADDY_SERVICE_HTTP_PORT}:80"
      - "${DOCKER_CADDY_SERVICE_HTTPS_PORT}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - cert:/etc/caddy
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    depends_on:
      - cups
    networks:
      - network

volumes:
  cert: null
  certbot-data: null

networks:
  network:
    name: ${DOCKER_NAME_PREFIX}_${DOCKER_NETWORK_NAME}
    external: true
