version: "3"

services:
  cups:
    container_name: ${DOCKER_NAME_PREFIX}_${DOCKER_CUPS_SERVICE_NAME}
    build:
      context: cups
      dockerfile: Dockerfile
      args:
        CUPS_ADMIN_USER: ${CUPS_ADMIN_USER}
        CUPS_ADMIN_PASSWORD: ${CUPS_ADMIN_PASSWORD}
    environment:
      CUPS_ADMIN: ${CUPS_ADMIN_USER}
      CUPS_ADMIN_PASS: ${CUPS_ADMIN_PASSWORD}
    networks:
      - network

  caddy:
    container_name: ${DOCKER_NAME_PREFIX}_${DOCKER_CADDY_SERVICE_NAME}
    build:
      context: caddy
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET}
    environment:
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    ports:
      - "${DOCKER_CADDY_SERVICE_HTTP_PORT}:80"
      - "${DOCKER_CADDY_SERVICE_HTTPS_PORT}:443"
    volumes:
      - ./var/www:/var/www
    depends_on:
      - cups
    networks:
      - network

networks:
  network:
    name: ${DOCKER_NAME_PREFIX}_${DOCKER_NETWORK_NAME}
    external: true
