version: '3'

services:
  cups:
    container_name: ${CONTAINER_NAME_PREFIX}_cups
    build:
      context: cups
      dockerfile: Containerfile
      args:
        CUPS_ADMIN_USER: ${CUPS_ADMIN_USER}
        CUPS_ADMIN_PASSWORD: ${CUPS_ADMIN_PASSWORD}
    environment:
      CUPS_ADMIN: ${CUPS_ADMIN_USER}
      CUPS_ADMIN_PASS: ${CUPS_ADMIN_PASSWORD}
    networks:
      - network

  caddy:
    container_name: ${CONTAINER_NAME_PREFIX}_caddy
    build:
      context: caddy
      dockerfile: Containerfile
      target: ${CONTAINER_TARGET}
    environment:
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    ports:
      - '${CONTAINER_CADDY_SERVICE_HTTP_PORT}:80'
      - '${CONTAINER_CADDY_SERVICE_HTTPS_PORT}:443'
    volumes:
      - ./var/www:/var/www
    depends_on:
      - cups
    networks:
      - network

networks:
  network:
    name: ${CONTAINER_NAME_PREFIX}_network
