[project]
name = "beam"
authors = [
	{ name = "AgriTheory", email = "support@agritheory.dev"}
]
description = "Barcode Scanning for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
	"pytest-order",
	"pytest",
	"python-barcode",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
indent = "\t"

[tool.semantic_release]
version_variables = [
	"beam/__init__.py:__version__",
	"pyproject.toml:version"
]

[tool.semantic_release.branches.version]
match = "version-15"
