// Copyright (c) 2024, AgriTheory and contributors
// For license information, please see license.txt

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    'delivery-note': RouteRecordInfo<'delivery-note', '/delivery-note', Record<never, never>, Record<never, never>>,
    'demand': RouteRecordInfo<'demand', '/demand', Record<never, never>, Record<never, never>>,
    'example': RouteRecordInfo<'example', '/example', Record<never, never>, Record<never, never>>,
    'job_card': RouteRecordInfo<'job_card', '/job_card/:id/', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'manufacture': RouteRecordInfo<'manufacture', '/manufacture', Record<never, never>, Record<never, never>>,
    'move': RouteRecordInfo<'move', '/move', Record<never, never>, Record<never, never>>,
    'purchase-receipt': RouteRecordInfo<'purchase-receipt', '/purchase-receipt', Record<never, never>, Record<never, never>>,
    'receive': RouteRecordInfo<'receive', '/receive', Record<never, never>, Record<never, never>>,
    'repack': RouteRecordInfo<'repack', '/repack', Record<never, never>, Record<never, never>>,
    'ship': RouteRecordInfo<'ship', '/ship', Record<never, never>, Record<never, never>>,
    'work_order': RouteRecordInfo<'work_order', '/work_order/:id/', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'operation': RouteRecordInfo<'operation', '/work_order/:id/operation/:id', { id: ParamValue<true>, id: ParamValue<true> }, { id: ParamValue<false>, id: ParamValue<false> }>,
    'workstation': RouteRecordInfo<'workstation', '/workstation', Record<never, never>, Record<never, never>>,
  }
}
