import frappe
import pytest

"""
1. Test that handling units are generated in a Purchase Receipt
2. Test that handling units are generated in a Purchase Invoice with update stock
3. Test handling units scanned into Stock Entry Transfer for Manufacture are preserved to SL
4. Test new handling units are generated by Stock Entry for Manufacture with scrap
5.
"""


@pytest.mark.skip()
def test_purchase_receipt():
	pass


@pytest.mark.skip()
def test_purchase_invoice():
	pass
