FROM debian:testing-slim

# Install Packages (basic tools, cups, basic drivers, HP drivers)
# printer-driver-all and printer-driver-gutenprint omitted (unavailable on Debian arm64)
RUN apt-get update \
    && apt-get install -y \
        sudo \
        whois \
        usbutils \
        cups \
        cups-client \
        cups-bsd \
        cups-filters \
        foomatic-db-compressed-ppds \
        openprinting-ppds \
        hpijs-ppds \
        hp-ppd \
        hplip \
        smbclient \
        printer-driver-cups-pdf \
        hplip \
        avahi-daemon \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ARG CUPS_ADMIN_USER=admin
ARG CUPS_ADMIN_PASSWORD=root
RUN useradd \
        --create-home \
        --groups sudo,lp,lpadmin \
        --shell=/bin/bash \
        --password=$(mkpasswd $CUPS_ADMIN_PASSWORD) \
        $CUPS_ADMIN_USER \
    && echo "$CUPS_ADMIN_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER $CUPS_ADMIN_USER

COPY cupsd.conf /etc/cups/cupsd.conf
RUN sudo chmod -R a+rwx /var/spool \
    && sudo chmod -R a+rwx /etc/cups

CMD [\
    "/usr/sbin/cupsd", \
    "-f" \
]
