name: Generate Matrix

on:
  push:
    branches:
      - version-14
      - version-15
  pull_request:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Generate Scanning Decision Matrix
        run: python3 ./beam/docs/generate_matrix.py
